---
- name: 拷贝JKD到目标服务器
  unarchive: src={{ jdk_pkg }} dest={{ jdk_dir }} mode=755

- name: 添加环境变量
  blockinfile:
    dest: /etc/profile
    create: yes
    backup: yes
    insertbefore: BOF
    block: |
      export JAVA_HOME={{ JAVA_HOME }}
      export JRE_HOME=/$JAVA_HOME/jre
      export CLASSPATH=:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib
      export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin:$CLASSPATH
      export PATH=$PATH:$JAVA_HOME/bin

- name: 
  shell: source /etc/profile
