---
- name: "add group"
  group: name={{ zabbix_group }}

- name: "add user"
  user:
    name={{ zabbix_user }}

- name: 拷贝配置文件
  template:
    src: zabbix_server.j2
    dest: /app/zabbix/etc/zabbix_server.conf

- name: 安装Zabbix Frontend
  shell: |
    rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    yum install zabbix-web-mysql -y
- name: 拷贝配置文件
  template:
    src: php.j2
    dest: /etc/php.ini

- name: install httpd
  yum:
    name: httpd
    state: installed

- name: start httpd
  service: 
    name: httpd
    state: started
    enabled: yes

- name: start zabbix
  shell: /app/zabbix/sbin/zabbix_server -c /app/zabbix/etc/zabbix_server.conf
